---
jwt:
  secret: dev!@##!211
  expired: 1
encrypt:
  keystring: 5ff37e7594e33ce1dcedd17644dc542d
  additional: secr3tsekalitem4n
debug: true
databases:
  postgres:
    host: localhost
    user: aprian1337
    password: root123
    dbname: thukul
    port: '5432'
    sslmode: disable
    timezone: Asia/Jakarta
  mongodb:
    port: '27017'
    username: ''
    password: ''
    cluster: localhost
    dbname: thukul
    collection:
      logger: logs
thirdparties:
  coinmarketcap:
    api_key: 00054b12-d501-46bf-b334-d3806d169fbd
context:
  timeout: 2
server:
  address:
    host: 0.0.0.0
    port: '1231'
smtp:
  host: smtp.gmail.com
  port: 587
  sender_name: Thukul Service - Noreply <thukulservice.noreply@gmail.com>
  email: thukulservice.noreply@gmail.com
  password: thukul111#!
