name: Running Unit Test

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

jobs:
  unit-test:
    name: "unit test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
#      - name: running unit test
#        run: go test ./... -cover

  build-push-docker:
    name: "Build image & push registry to dockerhub"
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
      - uses: actions/checkout@v2
#      - name: add config.json
#        env:
#          CONFIG_JSON: ${{secrets.CONFIG_JSON}}
#        run: echo "$CONFIG_JSON" > configs/env/config.yaml
      - name: build docker
        run: docker build -t aprian1337/shiva:1.0.0 .
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: push image to registry docker hub
        run: docker push aprian1337/thukul:1.0.0